version: '3.7'

services:
#  db:
#    image: postgres:10.1-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
  rest:
    build: .
    command: python /Bizzy/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Bizzy
    ports:
      - 8000:8000
#    depends_on:
#      - db