// users constants
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS'

// user profile constants
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';

export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED';

export const GET_USER_RECORDS_ALL_SUCCESS = 'GET_USER_RECORDS_ALL_SUCCESS';

export const GET_USER_RECORDS_ALL_FAILED = 'GET_USER_RECORDS_ALL_FAILED';

export const GET_USER_RECORDS_ACTIVE_SUCCESS = 'GET_USER_RECORDS_ACTIVE_SUCCESS';

export const GET_USER_RECORDS_ACTIVE_FAILED = 'GET_USER_RECORDS_ACTIVE_FAILED';

export const POST_RECORD_SUCCESS = 'POST_RECORD_SUCCESS';

export const POST_RECORD_FAILED = 'POST_RECORD_FAILED';

export const PATCH_RECORD_SUCCESS = 'PATCH_RECORD_SUCCESS';

export const PATCH_RECORD_FAILED = 'PATCH_RECORD_FAILED';

export const REMOVE_USER_RECORD_SUCCESS = 'REMOVE_USER_RECORD_SUCCESS';

export const REMOVE_USER_RECORD_FAILED = 'REMOVE_USER_RECORD_FAILED';

export const RESET_PROFILE = 'RESET_PROFILE';

export const RESET_RECORDS = 'RESET_RECORDS';

// services constants
export const POST_SERVICE_SUCCESS = 'POST_SERVICE_SUCCESS';

export const POST_SERVICE_FAILED = 'POST_SERVICE_FAILED';

export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';

export const GET_SERVICES_FAILED = 'GET_SERVICES_FAILED';

export const PATCH_SERVICE_SUCCESS = 'PUT_SERVICE_SUCCESS';

export const PATCH_SERVICE_FAILED = 'PUT_SERVICE_FAILED';

// arrivals constants
export const GET_ARRIVALS_BY_DATE_SUCCESS = 'GET_ARRIVALS_BY_DATE_SUCCESS';

export const GET_ARRIVALS_BY_DATE_FAILED = 'GET_ARRIVALS_BY_DATE_FAILED';

export const DELETE_ARRIVAL_SUCCESS = "DELETE_ARRIVAL_SUCCESS";