export const ON_FORM_CHANGE = 'ON_FORM_CHANGE';

export const REQUEST_MEMBERS_SUCCESS = 'REQUEST_MEMBERS_SUCCESS';

export const REQUEST_MEMBERS_FAILED = 'REQUEST_MEMBERS_FAILED';

export const REQUEST_USER_PROFILE_RESET = 'REQUEST_USER_PROFILE_RESET'

export const REQUEST_USER_PROFILE_SUCCESS = 'REQUEST_USER_PROFILE_SUCCESS';

export const REQUEST_USER_PROFILE_FAILED = 'REQUEST_USER_PROFILE_FAILED';

export const REQUEST_POST_NEW_SERVICE_SUCCESS = 'REQUEST_POST_NEW_SERVICE_SUCCESS';

export const REQUEST_POST_NEW_SERVICE_FAILED = 'REQUEST_POST_NEW_SERVICE_FAILED';

export const REQUEST_GET_SERVICES_SUCCESS = 'REQUEST_GET_SERVICES_SUCCESS';
    
export const REQUEST_GET_SERVICES_FAILED = 'REQUEST_GET_SERVICES_FAILED';

export const REQUEST_UPDATE_OPTION_SUCCESS = 'REQUEST_UPDATE_OPTION_SUCCESS';

export const REQUEST_UPDATE_OPTION_FAILED = 'REQUEST_UPDATE_OPTION_FAILED';