export const INPUT_CHANGE = 'INPUT_CHANGE';

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';

export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED';

export const GET_USER_RECORDS_SUCCESS = 'GET_USER_RECORDS_SUCCESS';
    
export const GET_USER_RECORDS_FAILED = 'GET_USER_RECORDS_FAILED';

export const POST_SERVICE_SUCCESS = 'POST_SERVICE_SUCCESS';

export const POST_SERVICE_FAILED = 'POST_SERVICE_FAILED';

export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
    
export const GET_SERVICES_FAILED = 'GET_SERVICES_FAILED';

export const PUT_SERVICE_SUCCESS = 'PUT_SERVICE_SUCCESS';

export const PUT_SERVICE_FAILED = 'PUT_SERVICE_FAILED';

export const POST_RECORD_SUCCESS = 'POST_RECORD_SUCCESS';

export const POST_RECORD_FAILED = 'POST_RECORD_FAILED';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'

export const DELETE_USER_RECORD_SUCCESS = 'DELETE_USER_RECORD_SUCCESS';

export const RESET_PROFILE = 'RESET_PROFILE';

export const RESET_RECORDS = 'RESET_RECORDS';

export const GET_ARRIVALS_BY_DATE_SUCCESS = 'GET_ARRIVALS_BY_DATE_SUCCESS';

export const GET_ARRIVALS_BY_DATE_FAILED = 'GET_ARRIVALS_BY_DATE_FAILED';

export const PATCH_RECORD_SUCCESS = 'PATCH_RECORD_SUCCESS';

export const PATCH_RECORD_FAILED = 'PATCH_RECORD_FAILED';